### ISSUE TITLE
Can not verify certificate when its intermedium CA has multiple name constraints

### ISSUE THREAD

**Issue by elemount** [briansmith/webpki#240] opened 2021-09-18 05:41 UTC
I'm using the webpki project to verify the tls client cert. One day, when the client cert is rotated, I find my client cert can not work anymore. 
After investigation, I find that the new cert's intermedium CA added multiple name constraints and then then webpki failed to build chain.
Here is what happens.
1. Entrance is `verify::verify_is_valid_tls_client_cert`
2. `verify::build_chain`
3. Inside this loop `    loop_while_non_fatal_error(intermediate_certs, |cert_der| {`, it called 
  ```rust
          untrusted::read_all_optional(potential_issuer.name_constraints, Error::BadDER, |value| {
              name::check_name_constraints(value, &cert)
          })?;
  ```
The `name::check_name_constraints(value, &cert)` returns Err and let the verification fails.

4. In my scenario, `name::check_name_constraints` fails on `    let excluded_subtrees = parse_subtrees(input, der::Tag::ContextSpecificConstructed1)?;`, which fails on `parse_subtrees`.
5. Inside the `parse_subtrees`, it fails on
```rust
        let subtrees = der::nested(inner, subtrees_tag, Error::BadDER, |tagged| {
            der::expect_tag_and_get_value(tagged, der::Tag::Sequence)
        })?;
```
Based on the RFC, the thing it try to do is read the total length of subtrees object, and then inside the subtrees object, it try to read each subtree.
In my scenario, subtrees tag is 161, length 120, then for each subtree,  the tag is 48, length 31, then the tag is 48, length is 15 then the tag is 48 and length is 68. It is a correct name constraint of a subtrees. 
But inside the code
```rust
pub fn nested<'a, F, R, E: Copy>(
    input: &mut untrusted::Reader<'a>,
    tag: Tag,
    error: E,
    decoder: F,
) -> Result<R, E>
where
    F: FnOnce(&mut untrusted::Reader<'a>) -> Result<R, E>,
{
    let inner = expect_tag_and_get_value(input, tag).map_err(|_| error)?;
    inner.read_all(error, decoder)
}
``` 
the inner is correct with length 120, then for the read_all, it read the first subtree and then fails, the code of `read_all` of `untrusted` package is
```rust
    /// Calls `read` with the given input as a `Reader`, ensuring that `read`
    /// consumed the entire input. If `read` does not consume the entire input,
    /// `incomplete_read` is returned.
    pub fn read_all<F, R, E>(&self, incomplete_read: E, read: F) -> Result<R, E>
    where
        F: FnOnce(&mut Reader<'a>) -> Result<R, E>,
    {
        let mut input = Reader::new(*self);
        let result = read(&mut input)?;
        if input.at_end() {
            Ok(result)
        } else {
            Err(incomplete_read)
        }
    }
```
which means the read_all does not mean run the decoder in a loop and prase all, but just run the decoder just once and see if it is at the end of the input. I guess the misuse of the `read_all` is the root cause of the failure. 

When the intermedium CA has multiple name constraints, the subtrees parser fails due to `incomplete_read` and then return `BadDer` error. 

Would you mind to fix it in recent days? It blocks me a lot due to this issue.

**Comment by briansmith** [comment] 2021-12-10 20:24
There is another issue about the name constraint parser being incorrect. I intend to fix this shortly. Closing this as a dupe of #20.

**Closed by briansmith** 2021-12-10 20:24 UTC
