### ISSUE TITLE
Doesn't accept omitted params for RSA

### ISSUE THREAD

**Issue by est31** [briansmith/webpki#102] opened 2019-06-11 17:44 UTC
These two certificates are rejected despite the spec saying that parsers MUST accept them:

```
-----BEGIN CERTIFICATE-----
MIIC9jCCAeCgAwIBAgIBKjALBgkqhkiG9w0BAQswLDEqMBAGA1UEAwwJTWFzdGVy
IENBMBYGA1UECgwPQ3JhYiB3aWRnaXRzIFNFMCIYDzE5NzUwMTAxMDAwMDAwWhgP
NDA5NjAxMDEwMDAwMDBaMCwxKjAQBgNVBAMMCU1hc3RlciBDQTAWBgNVBAoMD0Ny
YWIgd2lkZ2l0cyBTRTCCASAwCwYJKoZIhvcNAQEBA4IBDwAwggEKAoIBAQC3t8Yw
9Xdm5z39XXQEJ5GZJUvp3gdf3PVog2LSHtamjF0imVRZUQuVe5tL1ateib+zsghf
QxweTNyLBuulD6tJruOyvYrRVPulBrhS4cWK0tQhuDbeV1U70TN0LIpHL3/8f3XP
qf9th/aO/AXwBafIoJtn2wM3YpMYEBHkoB1m61R3d3Gky65NBfl6LvGoKB0u59SD
vnIK2FZjZBAm/nw246JLSSuqWrIQnZ7UzH5cWAgrmE72nrgaH2qbs3P2VmCaeVlM
4hJYxI1IrRftyUBo0A+I3Y4n3iISns3aI8NN/H60KdnCvIUI07eH5N8ZwnK9U9rG
rdQZ0GZHlLmks1SHAgMBAAGjJTAjMCEGA1UdEQQaMBiCC2NyYWJzLmNyYWJzggls
b2NhbGhvc3QwCwYJKoZIhvcNAQELA4IBAQBNHHRRRDwO+We3ItJldvoy+n6qw4fD
MDWQXIgSeHHiDJ9lfPOGtzQYy+ODd7Y/+zcEYXWDg1gvDluz3FUt7LZhwifSupXs
UWPCi/BxwzCOy6gwU8mA9omhq0mM7m5HjwFI4XNbNMuJL0rkFIXuVfKYILCmUvXh
Izjrp6jHeQ+VjKYUylYwQmJTXTNBNEuQV2JbLSmKzNuPlvCIAd8KjHLpuXDVd400
XDgDtuBqo7MJ1xhozfrZtHRyDHjg0vDjaRgGedg3KvN+F4tO7BZooJNB77LwKhTR
ZgKb9JwaSEWtJF5vomES1r7wSEAfKQB377u6rwX+YiytwVJrzarjpSax
-----END CERTIFICATE-----
```

```
-----BEGIN CERTIFICATE-----
MIIC+DCCAeKgAwIBAgIBKjALBgkqhkiG9w0BAQswLDEqMBAGA1UEAwwJTWFzdGVy
IENBMBYGA1UECgwPQ3JhYiB3aWRnaXRzIFNFMCIYDzE5NzUwMTAxMDAwMDAwWhgP
NDA5NjAxMDEwMDAwMDBaMCwxKjAQBgNVBAMMCU1hc3RlciBDQTAWBgNVBAoMD0Ny
YWIgd2lkZ2l0cyBTRTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALe3
xjD1d2bnPf1ddAQnkZklS+neB1/c9WiDYtIe1qaMXSKZVFlRC5V7m0vVq16Jv7Oy
CF9DHB5M3IsG66UPq0mu47K9itFU+6UGuFLhxYrS1CG4Nt5XVTvRM3Qsikcvf/x/
dc+p/22H9o78BfAFp8igm2fbAzdikxgQEeSgHWbrVHd3caTLrk0F+Xou8agoHS7n
1IO+cgrYVmNkECb+fDbjoktJK6pashCdntTMflxYCCuYTvaeuBofapuzc/ZWYJp5
WUziEljEjUitF+3JQGjQD4jdjifeIhKezdojw038frQp2cK8hQjTt4fk3xnCcr1T
2sat1BnQZkeUuaSzVIcCAwEAAaMlMCMwIQYDVR0RBBowGIILY3JhYnMuY3JhYnOC
CWxvY2FsaG9zdDALBgkqhkiG9w0BAQsDggEBAFjY0nYWg+PTi0Px5trC7SPUCt2+
LUvc6VoCx6+RWXWGglkVgN60tyZ5tl4GSizrMdFL0IpXScM2hn0e0KMOdSqXldo9
/4ypRLKkCEbXlWVYWxoBf5H/942I2ndxA1eJ+eFj1H5plvZ0TfkhO+3Rr+/cm17Q
G9W+BojiBIBizyw0YZu5yWb4QkQCN35dMdNAITub45VkhrrV70VOrbdgxNXPzGSp
IJGLaDXEcHkNAxaay5PAYmVXLACLjDbDHCl66OoYHVQ5RwtvQabT6OnME4FGUug6
rJT08ZZ+Rag+/e3oEfog3M6dZIoF9TPiMH4AaDQbr1jHg5yUXFknxwPPHfQ=
-----END CERTIFICATE-----
```

Quoting the spec: https://tools.ietf.org/html/rfc4055#section-5

> When any of these four object identifiers appears within an
   AlgorithmIdentifier, the parameters MUST be NULL.  Implementations
   MUST accept the parameters being absent as well as present.

Yes, the parameters are not NULL in these certs, but omitted, but the spec says that parsers must accept certs with absent parameters, too.

**Comment by briansmith** [comment] 2019-06-11 18:56
@est31 Which software generated these certificates?

**Comment by est31** [comment] 2019-06-11 19:17
@briansmith my own rcgen crate did, while I was adding RSA key generation support. Now it adds the NULL params as the spec requires. You can test it yourself by cloning https://github.com/est31/rcgen and changing `write_null_params : true,` to `write_null_params : false,` in the only place it occurs in lib.rs and then doing `cargo test _given`. You'll see that openssl has no problems with the change while webpki rejects such certificates.

**Comment by briansmith** [comment] 2019-06-11 20:41
@est31 Thanks! Since everything is working now, I'm going to close this as a dupe of #97.

**Closed by briansmith** 2019-06-11 20:41 UTC

**Comment by est31** [comment] 2019-06-11 20:45
Oh sorry, didn't know that it had been reported before.
